#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := motor-driver-normal-example-app

include $(IDF_PATH)/make/project.mk

